export const REQUEST = {
  ROOM: '/rooms',
  ROOM_JOIN: '/rooms/{roomId}/participations',
  ROOM_LEAVE: '/rooms/{roomId}/leave',
  ROOM_PARTICIPATED: '/rooms/participations',
  KAKAO: '/auth/kakao',
  LOGIN: '/auth/login',
  SIGNUP: '/auth/register/profile',
  CERTIFY_CODE: '/auth/phone/verify',
  CERTIFY_PHONE: '/auth/phone/send',
  CERTIFY_STUDENT: '/check/student-card',
  USER_INFO: '/auth/members/profile',
  UPDATE_USER: '/members/profile',
  REGISTER_TICKET: '/coupons',
};
